services:
  core:
    image: whatup/whatupcore
    build: ./src/whatupcore/
    environment:
      - KEY_DIR=/usr/src/whatupcore-data/keys/
      - STORAGE_DIR=/usr/src/whatupcore-data/storage/
    volumes:
      - ./data/whatupcore:/usr/src/whatupcore-data/storage/
      - ./data/keys/:/usr/src/whatupcore-data/keys/

  bot-archive:
    image: whatup/whatupy
    build: ./src/whatupy/
    links:
      - core
    environment:
      - WHATUPY_CERT=/usr/src/whatupy-data/static/cert.pem
      - WHATUPY_CONTROL_GROUPS=c+c-prod@g.us 33671714377@s.whatsapp.net # c+c-prod + micha
    volumes:
      - ./src/whatupcore:/usr/src/whatupy/whatupy/whatupcore
      - ./data/keys/cert.pem:/usr/src/whatupy-data/cert.pem
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    command: sh -c "whatupy --host core --cert /usr/src/whatupy-data/cert.pem archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/*"
