secrets:
  ssl-key:
    file: ./data/keys/key.pem
  ssl-cert:
    file: ./data/keys/cert.pem
  postgres-passwd:
    file: ./data/static/dev/postgres-passwd.secret

services:
  whatup:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupcore2
    build: ./whatupcore2/
    environment:
      - STORAGE_DIR=/usr/src/whatupcore-data/storage/
    secrets:
      - ssl-cert
      - ssl-key
    volumes:
      - ./data/whatupcore2/db/:/db/
    command: rpc --log-level=DEBUG

  db:
    image: postgres:15-alpine
    secrets:
      - postgres-passwd
    env_file:
      - .env
    volumes:
      - ./data/db/:/var/lib/postgresql/data
      - ./scripts/postgres-multi-databases.sh:/docker-entrypoint-initdb.d/postgres-multi-databases.sh
    ports:
      - 5432:5432

  bot-archive:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us 33671714377@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    command: whatupy --host whatup --cert /run/secrets/ssl-cert archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/

  bot-groupmanager:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us 33671714377@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
      - postgres-passwd
    env_file:
      - .env
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
    command: sh -c "whatupy --host whatup --cert /run/secrets/ssl-cert groupmanagerbot --database-url \"postgresql://$${POSTGRES_USER}:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" /usr/src/whatupy-data/sessions/"

  bot-database:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us 33671714377@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
      - postgres-passwd
    env_file:
      - .env
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/archive/:ro
    command: sh -c "whatupy --host whatup --cert /run/secrets/ssl-cert databasebot --database-url \"postgresql://$${POSTGRES_USER}:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" /usr/src/whatupy-data/sessions/"

  bot-database-load-archive:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - POSTGRES_DATABASE=messages
    secrets:
      - postgres-passwd
    env_file:
      - .env
    profiles:
      - donotstart
    volumes:
      - ./data/message-archive/:/archive/:ro
    command: sh -c "whatupy databasebot-load-archive --database-url \"postgresql://$${POSTGRES_USER}:$$( cat $${POSTGRES_PASSWORD_FILE})@db/$${POSTGRES_DATABASE}\" '/archive/*@*/*_*.json'"

  bot-onboard-bulk:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us 33671714377@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
    profiles:
      - donotstart
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    entrypoint: whatupy --host whatup --cert /run/secrets/ssl-cert onboard-bulk --credentials-dir /usr/src/whatupy-data/sessions/
