secrets:
  ssl-key:
    file: ./data/keys/key.pem
  ssl-cert:
    file: ./data/keys/cert.pem
  postgres-whatupdb-passwd:
    file: ./data/static/dev/postgres-whatupdb-passwd.secret
  postgres-messages-passwd:
    file: ./data/static/dev/postgres-messages-passwd.secret
  postgres-whatupcore-passwd:
    file: ./data/static/dev/postgres-whatupcore-passwd.secret

services:
  whatup:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupcore2
    platform: linux/x86_64
    build: ./whatupcore2/
    env_file:
      - .env
    environment:
      - USE_SSL=true
      - APP_NAME_SUFFIX=$APP_NAME_SUFFIX
      - ENC_KEY_SALT=kajsdfhkajsdfhaksdjfhkjasdfhskd
      - POSTGRES_DATABASE=whatupcore
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-whatupcore-passwd
    links:
      - db
    secrets:
      - ssl-cert
      - ssl-key
      - postgres-whatupcore-passwd
    command: rpc --log-level DEBUG

  db:
    image: postgres:15-alpine
    secrets:
      - postgres-whatupdb-passwd
      - postgres-messages-passwd
      - postgres-whatupcore-passwd
    env_file:
      - .env
    volumes:
      - ./data/db/:/var/lib/postgresql/data
      - ./scripts/initdb/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  bot-archive:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us anon.NlUiJWkTKZtZ7jgGVob9Loe4vkHphhoBJJQ-T-Niuuk.v001@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    command: whatupy --debug --host whatup --cert /run/secrets/ssl-cert archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/

  bot-debug:
    # run with,
    #   $ docker compose run --build --service-ports bot-debug  /usr/src/whatupy-data/sessions/<target-session>.json
    # and then connect with,
    #   $ rlwrap nc localhost 6666
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us 33671714377@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
    ports:
      - 6666:6666
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    entrypoint: whatupy --host whatup --cert /run/secrets/ssl-cert debugbot --host 0.0.0.0 --port 6666
    profiles:
      - donotstart

  bot-database:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us anon.NlUiJWkTKZtZ7jgGVob9Loe4vkHphhoBJJQ-T-Niuuk.v001@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
      - postgres-messages-passwd
    env_file:
      - .env
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
    command: sh -c "whatupy --host whatup --cert /run/secrets/ssl-cert databasebot --database-url \"postgresql://messages:$$( cat $${POSTGRES_MESSAGES_PASSWORD_FILE})@db/messages\" /usr/src/whatupy-data/sessions/"

  bot-database-load-archive:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - POSTGRES_DATABASE=messages
    secrets:
      - postgres-messages-passwd
    profiles:
      - donotstart
    volumes:
      - ./data/message-archive/:/usr/src/whatupy-data/archive/:ro
    #command: sh -c "whatupy --debug databasebot-load-archive --database-url \"postgresql://messages:$$( cat $${POSTGRES_MESSAGES_PASSWORD_FILE})@db/messages\" '/usr/src/whatupy-data/archive/120363023974439113@g.us/*_*.json'"
    command: sh -c "ls /usr/src/whatupy-data/archive/ | xargs -P 6 -I{} whatupy databasebot-load-archive --database-url \"postgresql://messages:$$( cat $${POSTGRES_MESSAGES_PASSWORD_FILE})@db/messages\" '/usr/src/whatupy-data/archive/{}/*_*.json'"

  bot-onboard-bulk:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
    secrets:
      - ssl-cert
    profiles:
      - donotstart
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: whatupy --host whatup --cert /run/secrets/ssl-cert onboard-bulk --credentials-url /usr/src/whatupy-data/sessions/

  bot-onboard:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - SESSION_NAME=$SESSION_NAME
    secrets:
      - ssl-cert
    profiles:
      - donotstart
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: whatupy --host whatup --cert /run/secrets/ssl-cert onboard --default-group-permission DENIED --credentials-url "/usr/src/whatupy-data/sessions/" ${SESSION_NAME}

  bot-chatbot:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
    command: whatupy --host whatup --cert /run/secrets/ssl-cert chatbot /usr/src/whatupy-data/sessions/

  bot-register:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363159470639781@g.us  # coolest friends
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-messages-passwd
    secrets:
      - postgres-messages-passwd
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: sh -c "whatupy --host whatup --cert /run/secrets/ssl-cert registerbot --database-url \"postgresql://messages:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" --sessions-url  /usr/src/whatupy-data/sessions/registered-users/ /usr/src/whatupy-data/sessions/erica.json"

  bot-userservices:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=XXXXX@g.us  # no one
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-messages-passwd
    secrets:
      - postgres-messages-passwd
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
    command: sh -c "whatupy --host whatup --cert /run/secrets/ssl-cert userservicesbot --database-url \"postgresql://messages:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" --sessions-url  /usr/src/whatupy-data/sessions/registered-users/ /usr/src/whatupy-data/sessions/erica.json"

  bot-user-archive:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=XXXXX@g.us  # NO ONE
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/registered-users/:/usr/src/whatupy-data/sessions/
      - ./data/message-archive-user/:/usr/src/whatupy-data/message-archive/
    command: whatupy --host whatup --cert /run/secrets/ssl-cert archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/
