secrets:
  ssl-key:
    file: ./data/keys/key.pem
  ssl-cert:
    file: ./data/keys/cert.pem

services:
  whatup:
    image: whatup/whatupcore2
    build: ./whatupcore2/
    environment:
      - STORAGE_DIR=/usr/src/whatupcore-data/storage/
    secrets:
      - ssl-cert
      - ssl-key
    volumes:
      - ./data/whatupcore2/db/:/db/

  bot-archive:
    image: whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-prod@g.us 33671714377@s.whatsapp.net # c+c-prod + micha
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    command: sh -c "whatupy --host whatup --cert /run/secrets/ssl-cert archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/*"
