secrets:
  whatup-ssl-key:
    file: ./data/keys/whatup.key.pem
  whatup-ssl-cert:
    file: ./data/keys/whatup.cert.pem
  photocop-ssl-key:
    file: ./data/keys/photocop.key.pem
  photocop-ssl-cert:
    file: ./data/keys/photocop.cert.pem
  postgres-whatupdb-passwd:
    file: ./data/static/dev/postgres-whatupdb-passwd.secret
  postgres-messages-passwd:
    file: ./data/static/dev/postgres-messages-passwd.secret
  postgres-whatupcore-passwd:
    file: ./data/static/dev/postgres-whatupcore-passwd.secret
  whatupcore-anon-key:
    file: ./data/static/dev/whatupcore-anon-key.secret
  whatupcore-login-proxy:
    file: ./data/static/dev/whatupcore-login-proxy.secret
  dashboard-google-auth:
    file: ./data/static/dev/dashboard-google-auth.secret
  photo-dna-key:
    file: ./data/static/dev/photo-dna-key.secret

services:
  whatup:
    platform: linux/x86_64
    build: ./whatupcore2/
    env_file:
      - .env
    environment:
      - USE_SSL=true
      - APP_NAME_SUFFIX=$APP_NAME_SUFFIX
      - ENC_KEY_SALT=kajsdfhkajsdfhaksdjfhkjasdfhskd
      - POSTGRES_DATABASE=whatupcore
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-whatupcore-passwd
      - PHOTOCOP_URI=photocop:3447
      - WHATUP_TLS_KEY=/run/secrets/whatup-ssl-key
      - WHATUP_TLS_CERT=/run/secrets/whatup-ssl-cert
      - PHOTOCOP_TLS_CERT=/run/secrets/photocop-ssl-cert
    links:
      - db
      - photocop
    secrets:
      - whatup-ssl-cert
      - whatup-ssl-key
      - photocop-ssl-cert
      - postgres-whatupcore-passwd
      - whatupcore-anon-key
      - whatupcore-login-proxy
    command: rpc --log-level DEBUG

  photocop:
    platform: linux/x86_64
    build: ./photo-cop/
    secrets:
      - photo-dna-key
      - photocop-ssl-cert
      - photocop-ssl-key
    environment:
      - PHOTOCOP_TLS_CERT=/run/secrets/photocop-ssl-cert
      - PHOTOCOP_TLS_KEY=/run/secrets/photocop-ssl-key
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    secrets:
      - postgres-whatupdb-passwd
      - postgres-messages-passwd
      - postgres-whatupcore-passwd
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whatupdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db/:/var/lib/postgresql/data
      - ./scripts/initdb/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  dashboard:
    platform: linux/x86_64
    build: ./diwi-dashboard/
    secrets:
      - dashboard-google-auth
    ports:
      - 8080:8080
    environment:
      - GOOGLE_AUTH_FILE=/run/secrets/dashboard-google-auth
      - JWT_SECRET=hjdfhaskdufhiudha8ty893uhfsdiluaidufh
      - DASHBOARD_AUTH_GROUP=diwi-dashboard-dev-micha@digitalwitnesslab.org
      - DASHBOARD_GS_PATH=gs://diwi-dashboard-test
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - PYTHONUNBUFFERED=1

  bot-archive:
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-dev@g.us # c+c-dev
    secrets:
      - whatup-ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    command: whatupy --debug --host whatup --cert /run/secrets/whatup-ssl-cert archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/

  bot-debug:
    # run with,
    #   $ docker compose run --build --service-ports bot-debug  /usr/src/whatupy-data/sessions/<target-session>.json
    # and then connect with,
    #   $ rlwrap nc localhost 6666
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-dev@g.us # c+c-dev
    secrets:
      - whatup-ssl-cert
    ports:
      - 6666:6666
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    entrypoint: whatupy --host whatup --cert /run/secrets/whatup-ssl-cert debugbot --host 0.0.0.0 --port 6666
    profiles:
      - donotstart

  bot-database:
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-prod@g.us # anon.NlUiJWkTKZtZ7jgGVob9Loe4vkHphhoBJJQ-T-Niuuk.v001@s.whatsapp.net # c+c-prod + micha
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-messages-passwd
    secrets:
      - whatup-ssl-cert
      - postgres-messages-passwd
    env_file:
      - .env
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/media/:/usr/src/whatupy-data/media/
    command: sh -c "whatupy --host whatup --cert /run/secrets/whatup-ssl-cert databasebot --database-url \"postgresql://messages:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" --media-base /usr/src/whatupy-data/media/ /usr/src/whatupy-data/sessions/"

  bot-database-load-archive:
    build: ./whatupy/
    links:
      - db
    environment:
      - POSTGRES_DATABASE=messages
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-messages-passwd
    secrets:
      - postgres-messages-passwd
    profiles:
      - donotstart
    volumes:
      - ./data/message-archive-user/:/usr/src/whatupy-data/archive/:ro
      - ./data/media/:/usr/src/whatupy-data/media/
      - ./data/lock/:/tmp/load-archive-lock/
    #command: sh -c "ls /usr/src/whatupy-data/archive/ | xargs -P 6 -I{} whatupy databasebot-load-archive --database-url \"postgresql://messages:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" --media-base /usr/src/whatupy-data/media/ '/usr/src/whatupy-data/archive/{}/*_*.json'"
    command: sh -c "whatupy --debug databasebot-load-archive --database-url \"postgresql://messages:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" --media-base /usr/src/whatupy-data/media/ --run-lock-path /tmp/load-archive-lock/ --run-name TEST123 '/usr/src/whatupy-data/archive/anon.My5_-a9dotXGbdGmlgiMb77Lho8e8CKOt-IpfVzV7YI.v001@g.us/*_*.json'"

  bot-onboard-bulk:
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
    secrets:
      - whatup-ssl-cert
    profiles:
      - donotstart
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: whatupy --host whatup --cert /run/secrets/whatup-ssl-cert onboard-bulk --credentials-url /usr/src/whatupy-data/sessions/

  bot-onboard:
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
      - SESSION_NAME=$SESSION_NAME
    secrets:
      - whatup-ssl-cert
    profiles:
      - donotstart
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: whatupy --host whatup --cert /run/secrets/whatup-ssl-cert onboard --default-group-permission READWRITE --credentials-url "/usr/src/whatupy-data/sessions/" ${SESSION_NAME}

  bot-chat:
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
    secrets:
      - whatup-ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
    command: whatupy --host whatup --cert /run/secrets/whatup-ssl-cert chatbot --response-time 3600 /usr/src/whatupy-data/sessions/

  bot-register:
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-dev@g.us # c+c-dev
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-messages-passwd
    secrets:
      - postgres-messages-passwd
      - whatup-ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: sh -c "whatupy --host whatup --cert /run/secrets/whatup-ssl-cert registerbot --database-url \"postgresql://messages:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" --sessions-url  /usr/src/whatupy-data/sessions/registered-users/ /usr/src/whatupy-data/sessions/beatrice.json"

  bot-userservices:
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-dev@g.us # c+c-dev
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-messages-passwd
    secrets:
      - postgres-messages-passwd
      - whatup-ssl-cert
    volumes:
      - ./data/sessions/beatrice.json:/usr/src/whatupy-data/beatrice.json:ro
      - ./data/sessions/registered-users/:/usr/src/whatupy-data/sessions/
      - ./data/public/:/data-public/
    command: sh -c "whatupy --debug --host whatup --cert /run/secrets/whatup-ssl-cert userservicesbot --database-url \"postgresql://messages:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" --public-path=/data-public/ --sessions-url  /usr/src/whatupy-data/sessions/ /usr/src/whatupy-data/beatrice.json"

  bot-user-archive:
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
      - WHATUPY_CONTROL_GROUPS=XXXXX@g.us  # NO ONE
    secrets:
      - whatup-ssl-cert
    volumes:
      - ./data/sessions/registered-users/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive-user/:/usr/src/whatupy-data/message-archive/
    command: whatupy --host whatup --cert /run/secrets/whatup-ssl-cert archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/

  bot-user-database:
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/whatup-ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-prod@g.us anon.NlUiJWkTKZtZ7jgGVob9Loe4vkHphhoBJJQ-T-Niuuk.v001@s.whatsapp.net # c+c-prod + micha
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-messages-passwd
    secrets:
      - whatup-ssl-cert
      - postgres-messages-passwd
    env_file:
      - .env
    volumes:
      - ./data/sessions/registered-users/:/usr/src/whatupy-data/sessions/:ro
      - ./data/media/:/usr/src/whatupy-data/media/
    command: sh -c "whatupy --debug --host whatup --cert /run/secrets/whatup-ssl-cert databasebot --database-url \"postgresql://messages:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" --media-base /usr/src/whatupy-data/media/ /usr/src/whatupy-data/sessions/"

  hash-gen:
    build: ./hash-gen/
    env_file:
      - .env
    profiles:
      - donotstart
    volumes:
      - ./data/media/:/usr/src/whatupy-data/media/
    
