secrets:
  ssl-key:
    file: ./data/keys/key.pem
  ssl-cert:
    file: ./data/keys/cert.pem
  postgres-passwd:
    file: ./data/static/dev/postgres-passwd.secret

services:
  whatup:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupcore2
    build: ./whatupcore2/
    environment:
      - STORAGE_DIR=/usr/src/whatupcore-data/storage/
      - USE_SSL=true
    secrets:
      - ssl-cert
      - ssl-key
    volumes:
      - ./data/whatupcore2/db/:/db/
    command: /whatupcore2 rpc --log-level=INFO

  db:
    image: postgres:15-alpine
    secrets:
      - postgres-passwd
    env_file:
      - .env
    volumes:
      - ./data/db/:/var/lib/postgresql/data
      - ./scripts/postgres-multi-databases.sh:/docker-entrypoint-initdb.d/postgres-multi-databases.sh
    ports:
      - 5432:5432

  bot-archive:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us anon.NlUiJWkTKZtZ7jgGVob9Loe4vkHphhoBJJQ-T-Niuuk.v001@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    command: whatupy --host whatup --cert /run/secrets/ssl-cert archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/micha.json

  bot-debug:
    # run with,
    #   $ docker compose run --build --service-ports bot-debug  /usr/src/whatupy-data/sessions/<target-session>.json
    # and then connect with,
    #   $ rlwrap nc localhost 6666
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us 33671714377@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
    ports:
      - 6666:6666
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    entrypoint: whatupy --host whatup --cert /run/secrets/ssl-cert debugbot --host 0.0.0.0 --port 6666
    profiles:
      - donotstart

  bot-database:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=120363104970691776@g.us anon.NlUiJWkTKZtZ7jgGVob9Loe4vkHphhoBJJQ-T-Niuuk.v001@s.whatsapp.net # cool friends + micha
    secrets:
      - ssl-cert
      - postgres-passwd
    env_file:
      - .env
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
    command: sh -c "whatupy --host whatup --cert /run/secrets/ssl-cert databasebot --database-url \"postgresql://$${POSTGRES_USER}:$$( cat $${POSTGRES_PASSWORD_FILE})@db/messages\" /usr/src/whatupy-data/sessions/"

  bot-database-load-archive:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - db
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - POSTGRES_DATABASE=messages
    secrets:
      - postgres-passwd
    env_file:
      - .env
    profiles:
      - donotstart
    volumes:
      - ./data/message-archive/:/usr/src/whatupy-data/archive/:ro
    #command: sh -c "whatupy --debug databasebot-load-archive --database-url \"postgresql://$${POSTGRES_USER}:$$( cat $${POSTGRES_PASSWORD_FILE})@db/$${POSTGRES_DATABASE}\" '/usr/src/whatupy-data/archive/120363023974439113@g.us/*_*.json'"
    command: sh -c "ls /usr/src/whatupy-data/archive/ | xargs -n 1 -P 6 -I{} whatupy databasebot-load-archive --database-url \"postgresql://$${POSTGRES_USER}:$$( cat $${POSTGRES_PASSWORD_FILE})@db/$${POSTGRES_DATABASE}\" '/usr/src/whatupy-data/archive/{}/*_*.json'"

  bot-onboard-bulk:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
    secrets:
      - ssl-cert
    profiles:
      - donotstart
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: whatupy --host whatup --cert /run/secrets/ssl-cert onboard-bulk --credentials-dir /usr/src/whatupy-data/sessions/

  bot-onboard:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - SESSION_NAME=
    secrets:
      - ssl-cert
    profiles:
      - donotstart
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: whatupy --host whatup --cert /run/secrets/ssl-cert onboard --credentials-dir /usr/src/whatupy-data/sessions/ ${SESSION_NAME}

  bot-chatbot:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
    command: whatupy --host whatup --cert /run/secrets/ssl-cert chatbot /usr/src/whatupy-data/sessions/

  bot-register:
    image: asia-south1-docker.pkg.dev/whatup-395208/whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    command: whatupy --host whatup --cert /run/secrets/ssl-cert registerbot /usr/src/whatupy-data/sessions/gertrude.json /usr/src/whatupy-data/sessions/registered-users/
