secrets:
  ssl-key:
    file: ./data/keys/key.pem
  ssl-cert:
    file: ./data/keys/cert.pem
  postgres-passwd:
    file: ./postgres-passwd-dev

services:
  whatup:
    image: whatup/whatupcore2
    build: ./whatupcore2/
    environment:
      - STORAGE_DIR=/usr/src/whatupcore-data/storage/
    secrets:
      - ssl-cert
      - ssl-key
    volumes:
      - ./data/whatupcore2/db/:/db/
    command: rpc --log-level=DEBUG

  db:
    image: postgres:15-alpine
    secrets:
      - postgres-passwd
    env_file:
      - ./docker-compose.env
    volumes:
      - ./data/db/:/var/lib/postgresql/data
      - ./scripts/postgres-multi-databases.sh:/docker-entrypoint-initdb.d/postgres-multi-databases.sh

  bot-archive:
    image: whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-prod@g.us 33671714377@s.whatsapp.net # c+c-prod + micha
    secrets:
      - ssl-cert
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/:ro
      - ./data/message-archive/:/usr/src/whatupy-data/message-archive/
    command: sh -c "whatupy --host whatup --cert /run/secrets/ssl-cert archivebot --archive-dir /usr/src/whatupy-data/message-archive/ /usr/src/whatupy-data/sessions/*"

  bot-onboard:
    image: whatup/whatupy
    build: ./whatupy/
    links:
      - whatup
    environment:
      - WHATUPY_CERT=/run/secrets/ssl-cert
      - WHATUPY_CONTROL_GROUPS=c+c-prod@g.us 33671714377@s.whatsapp.net # c+c-prod + micha
    secrets:
      - ssl-cert
    profiles:
      - donotstart
    volumes:
      - ./data/sessions/:/usr/src/whatupy-data/sessions/
    entrypoint: whatupy --host whatup --cert /run/secrets/ssl-cert onboard --credentials-dir /usr/src/whatupy-data/sessions/
