"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetPhotoHashRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PHOTO_FIELD_NUMBER: builtins.int
    Photo: builtins.bytes

    def __init__(self, *, Photo: builtins.bytes=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['Photo', b'Photo']) -> None:
        ...
global___GetPhotoHashRequest = GetPhotoHashRequest

@typing.final
class PhotoCopHash(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    Value: builtins.bytes

    def __init__(self, *, Value: builtins.bytes=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['Value', b'Value']) -> None:
        ...
global___PhotoCopHash = PhotoCopHash

@typing.final
class CheckPhotoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PHOTO_FIELD_NUMBER: builtins.int
    GETHASH_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    Photo: builtins.bytes
    GetHash: builtins.bool
    Priority: builtins.int

    def __init__(self, *, Photo: builtins.bytes=..., GetHash: builtins.bool=..., Priority: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['GetHash', b'GetHash', 'Photo', b'Photo', 'Priority', b'Priority']) -> None:
        ...
global___CheckPhotoRequest = CheckPhotoRequest

@typing.final
class PhotoCopDecision(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ISMATCH_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    MATCHES_FIELD_NUMBER: builtins.int
    IsMatch: builtins.bool

    @property
    def Hash(self) -> global___PhotoCopHash:
        ...

    @property
    def Matches(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MatchInfo]:
        ...

    def __init__(self, *, IsMatch: builtins.bool=..., Hash: global___PhotoCopHash | None=..., Matches: collections.abc.Iterable[global___MatchInfo] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['Hash', b'Hash']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['Hash', b'Hash', 'IsMatch', b'IsMatch', 'Matches', b'Matches']) -> None:
        ...
global___PhotoCopDecision = PhotoCopDecision

@typing.final
class MatchInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOURCE_FIELD_NUMBER: builtins.int
    DISTANCE_FIELD_NUMBER: builtins.int
    VIOLATIONS_FIELD_NUMBER: builtins.int
    Source: builtins.str
    Distance: builtins.int

    @property
    def Violations(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        ...

    def __init__(self, *, Source: builtins.str=..., Distance: builtins.int=..., Violations: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['Distance', b'Distance', 'Source', b'Source', 'Violations', b'Violations']) -> None:
        ...
global___MatchInfo = MatchInfo