apiVersion: v1
data:
  postgres-passwd: ZmQ2ZmYyZjcxNjNhMmUxYTllYTgyNDE5YmFiM2QwYTMwYzEwNWUxMzEyNmE1YWY1NDIzYTZjOGZiM2EwOTZiOAo=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-passwd
  name: postgres-passwd
  namespace: default
type: Opaque
