config:
  gcp:project: whatup-prod
  gcp:region: us-central1
  gcp:zone: us-central1-a
  google-native:project: whatup-prod
  google-native:region: us-central1
  google-native:zone: us-central1-a
  whatup:bqDatasetRegion: US
  whatup:control_groups:
    - c+c-prod@g.us # c+c-prod
    - pilot2@g.us # pilot2
    - pilot4@g.us # pilot4
  whatup:dashboards:
    - authGroups:
        - whatup-data-viewers@digitalwitnesslab.org
      clientCredsKey: dashboardClientCreds
      domain: dashboard
      gsPath: gs://diwi-dashboard-prod-3a9b/
      jwtKey: dashboardJWT
    - authGroups:
        - whatup-data-viewers@digitalwitnesslab.org
      clientCredsKey: dashboardClientCreds
      domain: gun-market
      gsPath: gs://gun-market/
      jwtKey: dashboardGunMarketJWT
  whatup:databases:
    - name: messages
      nameShort: msg
      passwordKey: msgPassword
    - name: whatupcore
      nameShort: wuc
      passwordKey: wucPassword
    - name: users
      nameShort: usr
      passwordKey: usrPassword
  whatup:dbRootPassword:
    secure: AAABAFv5380VKtGKsITAlanHzAjVOci131oKQuXaBeMKjjMjcus/2GOnETe9CqKmgKepFb8jIZ6IXkPuAxzHsDugI2epgcevxpU/7/WcHOdf6zO9PxMR+iV8N43uKnmLc4FY0VhG4V7J6RVGejPwJN5Um1Aq0y4LsndbOsUmxPAhbRHzScK7Zc9TcTYHF+uMdDunFa/q6L0FOligDP4Ckw==
  whatup:enabledServices:
    - bot-archive
    - bot-db
    - bot-user-services
    - bot-register
    - diwi-dashboard
  whatup:isProd: "true"
  whatup:loadArchiveJob: "true"
  whatup:machineTypes:
    - serviceName: whatupcore2
      type: E2Medium
    - serviceName: bot-db
      type: E2Medium
    - serviceName: bot-archive
      type: E2Medium
    - serviceName: bot-register
      type: E2Micro
    - serviceName: bot-chat
      type: E2Micro
    - serviceName: null
      type: E2Small
  whatup:msgPassword:
    secure: AAABAPft8aaBuey6IpzgenxXImjFxNmYYOckUp+a9XrXmlLU13C4H6ajxAdKJ7JMFg1UOYvLWWESI7iWpGBc6pCRb/Cg6/aGbqyNi5iY+aqYlPaiyYEvolFyuMP77H1a4/83ict2ooffR95bDlaHdpo98pjweIUb7sbwu1E0ojk5JOvGycahMxszFY/3zbvgipiXsvkKjoXl4fKXJageUw==
  whatup:primary_bot_name: lauren
  whatup:rootDomain: g.digitalwitnesslab.org
  whatup:temp_bucket_ttl_days: "1"
  whatup:translationEnabled: "true"
  whatup:multimodalEnabled: "true"
  whatup:usrPassword:
    secure: AAABAEAmTtZjTL1be4uv48gNkr05KhIaCy+60iiwKazYu0iQlz1ZO5jLVVhDumQdfJdD3LwjENDhQqsLALeAN9eg7aGAqXsTWHhSamaeO0gWfrODBkUDAnh+CpZh5DJ1twPYltbJ/735lL/EXF4fFUeNVcUM9bKWReANpo/nC3SyG3hd5/lw8yIK7ZqljunpIzNriBFqilGqmd3Q6zC5/Q==
  whatup:whatupAnonKey:
    secure: AAABAKj9qj4TvvSCPvuJqDb4cIfZsVvrEzr4SoOIGPcpsNPAF+q6GUxhpWAy5WAlEQKdc7ZV3Nq49q7eOs3Fc+kHlcntWMWoVCxippyIqJrm+xAO0tRHoE+k+4Gb9/ws
  whatup:whatupLoginProxy:
    secure: AAABAJ73BVatNUgl6ZB7l8GsfSqHwggT3R9DDjHiN83Lr8xr7x/xllykuzvcLoaK9+XOSSAfPZXtetsMyaM9MWpFnDkJ0NESRNYJtNYzbilfXax2Szo2AVtTW8PvuRiRMbifvoWl3zW/KS2nkKE4yikfCUDCHinzfQ==
  whatup:whatupSalt:
    secure: AAABAIvDi1nskbCLLSHpB8mwBbx53znHjUTLwPq2AfB1RKz3i602Znzxl/VNGmmrFU5Tx7P7FH9If9ykF+SF4QD9ed23EItQGLVqArCXK6tynDwnOUwi6IbU89fWscfWoceGAJMMsc+GlJJT5sVPogMkcextSmJ17s+6t1vvBXjxfYV/SDSg6QZPazAv2x6/ZPXDdFLL7jLDjYZ8GCHIOQ==
  whatup:wucPassword:
    secure: AAABALU0dLM7ZTaA3CyuRgWt0MiDPRhLcQI55QDU/TqT4iNSXFCfluMAPM3o7OW5hZt9WY/5Ffqt0Gajhs+S+/Muy6XIpVQ0AHVJjQ+//YuSx7G4IJhSHLhx/2LRzIiCyTmVrs4GvK3QomONoq8IsryAwPkbPtsrk+SmlnryPOjJDKxv6lwMiRJ+DUzosbw9Tupl1yBxMvZ9aLjkpb9M8g==
  whatup:dashboardClientCreds:
    secure: AAABAEDPxMuaAL4fYNGaEJbcaoxu6bGgetExNwnn9AFKlajcJ/y3oFmzdiR1SFC+JS/QdTilEVfEMgMiBsEd0b58sow/TpXJqbmTCwiDt+sOOYv8X4S4Xejmo4tEYRVD4/9XSwFkHWDq9+8DAiPYDBbPLmURizdWV3skF1IvzFhRCL8HKlQ4RifN9tz9oc/S6Hb5N0Blf7CZkEWohrws7EClp8Ilvz2lWBr+IK//bI6dFIHckU6Tav1J6GSxLChZbRcicO+Z9rxkijPzW6slaADZvLCpvsLkglhQApQMOa1f4IsBLUzq+yfXexDNSYVglr4+v4jtg+GUF6qxf2R71bTrUrTxCUof7oOkNeBqvLP0NBKfkRrrrDq1KemA+uG905k3M3KYzr28QEfYGR3J9GuxFbWtlpCCdsESN2ouDnsW2IIWewiG8/KRAdjfq4vyqCN07LOvDBbxtF2gXsdMQwl8HgAGW8ljuT+bRRznVNFjzdHEYLBYkL1tgHX69jO0v41oFJmO+VvczfHkUVAPApxUA1NpGkuFKtLbPKxLKdfLrLcGBnlgPnMOIx3j9vPqaXmQqLw1gXtDnXJN4Tq9Y3HdYKOaoXWA7m3el8U=
  whatup:dashboardJWT:
    secure: AAABAEP7TNCnmIczTMdLjHWbaMNyNySUzS/Xm5r/efxCwUaOwepdIp30Tn6oYmLohvRfgQAoQz9kHn2kN8P+VXHr/4ZVhgw1xvZpMNQTFt2A8NVy53XrVztrtUsYRMCzT7rMAJREarpVUZDWpGgw5WjAxP8huExO5bGexwdqg5BS9pLI1zVo3hInuDojx8zApBzeL+Y0bgFqEJttfNrM0A==
  whatup:dashboardGunMarketJWT:
    secure: AAABADblUjWTVyCOA5TBs6azo31uG6kYZDBEfSCDcUvHONl6I/1lKQjprad6V6KY7kQmEFoPnxo97jBYarazNQAPvAO7MWwPmTvA/8UyvC+aJTsGCSjAL8i1XzOmOHXjFjOcZB3uUPpOxbG3/+3KbSbi0zEX2JKEf4iqXKfBwHb/EHSdBox4OEXzBrfofLK73bRFzbbIgLMyTUNkzT3Fbg==
