name: Infrastructure CI

on:
  push:
    branches: main
    paths:
      - infrastructure/**
      - .github/workflows/ci.yml

  pull_request:
    paths:
      - infrastructure/**
      - .github/workflows/ci.yml

concurrency:
  group: ci_${{ github.ref }}
  # Never cancel in-progress push builds as it could leave the
  # infrastructure in a bad state.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read # Allows actions/checkout to read the repo.
  id-token: write

jobs:
  preview-or-deploy-test-infra:
    if: github.base_ref == 'main'
    uses: ./.github/workflows/pulumi.yml
    secrets: inherit
    with:
      gh-environment: test

  preview-or-deploy-prod-infra:
    if: github.base_ref == 'production'
    uses: ./.github/workflows/pulumi.yml
    secrets: inherit
    with:
      gh-environment: prod
