name: Infrastructure CI

on:
  push:
    branches: main
    paths:
      - infrastructure/**
      - .github/workflows/lint-infra.yml

  pull_request:
    paths:
      - infrastructure/**
      - .github/workflows/lint-infra.yml

  workflow_dispatch:
    inputs:
      command:
        description: up or destroy? (cannot run destroy if stack name is prod.)
        default: "up"
        required: true
      stackName:
        type: choice
        required: true
        description: Pulumi stack name
        default: test
        options:
          - test
          - prod

permissions:
  contents: read # Allows actions/checkout to read the repo.
  id-token: write

jobs:
  pulumi:
    env:
      PULUMI_COMMAND: preview
      PULUMI_STACK_NAME: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy workflow_dispatch inputs
        if: github.event_name == 'workflow_dispatch'
        env:
          COMMAND_INPUT: ${{ github.event.inputs.command }}
          STACK_NAME_INPUT: ${{ github.event.inputs.stackName }}
        run: |-
          echo "PULUMI_COMMAND=$COMMAND_INPUT" >> "$GITHUB_ENV"
          echo "PULUMI_STACK_NAME=$STACK_NAME_INPUT" >> "$GITHUB_ENV"

      - id: auth
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          project_id: whatup-deploy
          workload_identity_provider: "<example-workload-identity-provider>"

      - id: gcloud
        name: "gcloud"
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

      - name: Run pulumi
        uses: pulumi/actions@v4
        with:
          command: ${{ env.PULUMI_COMMAND }}
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: infrastructure
          comment-on-pr: ${{ github.event_name == 'pull_request' }}
