name: Lint infrastructure

on:
  pull_request:
    paths: infrastructure/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: make lint
        working-directory: infrastructure
